version: '3'

services:
  web:
    build: .
    command: gunicorn happy_grad_fin.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3  # Persist the SQLite database file
#      - ./static:/app/static  # Optional: Mount the static files directory if needed
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1  # Optional: Control Django's DEBUG setting via an environment variable

volumes:
  db_data:
