version: '3'

services:
  web:
    build: .
    command: gunicorn happy_grad_fin.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
      #- ./static:/app/static
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=happy_grad_fin.settings  # Set Django settings module
