# Generated by Django 4.1 on 2024-10-15 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_matcher', '0005_alter_document_created_alter_document_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 15, 18, 20, 54, 499594, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='document',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 22, 18, 20, 54, 499391, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 15, 18, 20, 54, 494165, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 15, 18, 20, 54, 494030, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 15, 18, 20, 54, 496988, tzinfo=datetime.timezone.utc)),
        ),
    ]
