# Generated by Django 4.1 on 2024-10-17 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_matcher', '0006_alter_document_created_alter_document_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 17, 17, 26, 50, 631466, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='document',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 24, 17, 26, 50, 631259, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 17, 17, 26, 50, 626509, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 17, 17, 26, 50, 626369, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 17, 17, 26, 50, 628929, tzinfo=datetime.timezone.utc)),
        ),
    ]
